### ISSUE TITLE
cat_relevel + missing

### ISSUE THREAD

**Issue by behinger** [TidierOrg/TidierCats.jl#8]
`cat_relevel` doesnt play well with missings

```julia
@test cat_relevel(CategoricalArray(["A","B",missing]),["B",missing,"A"])|>levels == ["B",missing,"A"]
```
(this could be a unittest to test the functionality)

This results in:

```julia
MethodError: no method matching cat_relevel(::CategoricalArrays.CategoricalVector{Union{Missing, String}, UInt32, String, CategoricalArrays.CategoricalValue{String, UInt32}, Missing}, ::Vector{Union{Missing, String}})

Closest candidates are:

cat_relevel(::CategoricalArrays.CategoricalArray, !Matched::Vector{String})

@ TidierCats C:\Users\behinger\.julia\packages\TidierCats\9gKGY\src\TidierCats.jl:26
```

Everything else works great so far!! Thanks for the very nice package

**Comment by drizk1** [comment]
Thank you for bringing this up! I'm happy you enjoy the package. 

I will work on getting this fixed so it's not an issue and getting the new version up soon

**Comment by behinger** [comment]
thanks! it might be as easy as allowing Missing in the type definition, but I didnt check. I for now replaced missing with "missing" ;-)

**Comment by drizk1** [comment]
I think so as well. Should have it up by the end of the week

**Comment by drizk1** [comment]
Update: I tried a few different ways and it appears this may not be as straightforward as I originally anticipated, but it will get fixed.

**Comment by drizk1** [comment]
Ok, just a few short weeks later, `cat_relevel` can now handle missing values.

```
cx = CategoricalArray(["A","B",missing]);

julia> print(levels(cx, skipmissing = false))
Union{Missing, String}["A", "B", missing]

julia> print(levels(cat_relevel(cx, ["B",missing,"A"]), skipmissing=false))
Union{Missing, String}["B", "A", missing]
```

do show missing levels,  `skipmissing=false` in `levels` must be set to false, and my understanding from the catarrays.jl documentation is that missing will get sorted to last.

so i think if you wanted to put missing somewhere other than last, replacing it with `"missing"` is maybe the easiest way. 

the new update will also have 

`cat_replace_missing(cat_array, "string_for_missing_values")` as function. its a simple wrapper but will be available.

sorry for the long delay and imperfect solution. 

Plz reopen the issue as needed
