### ISSUE TITLE
In Release v0.1.1, cat_collapse() example in README fails with UnDefVarERROR.

### ISSUE THREAD

**Issue by proudindiv** [TidierOrg/TidierCats.jl#9]
In README ["Examples" ](https://github.com/TidierOrg/TidierCats.jl#examples) at ["cat_collapse()"](https://github.com/TidierOrg/TidierCats.jl#cat_collapse), I get error **"UndefVarError: `.$(Expr(:escape, :Dict))` not defined:"**. (The same thing happens if I run it in the repl.)
![Stacktrace](https://github.com/TidierOrg/TidierCats.jl/assets/7218387/f08ee46b-0dbb-4264-9ae0-82a82ad7952e)

However, the second argument function runs ok.
![argument](https://github.com/TidierOrg/TidierCats.jl/assets/7218387/2c105a0a-2756-4158-ba06-94594a274d9d)

 I'm running julia Version 1.10.0 (2023-12-25) in juypter 4.9.1-1.
![Status](https://github.com/TidierOrg/TidierCats.jl/assets/7218387/db89265f-c0a2-45b4-9b86-37b37fef01be)
![linuxmint](https://github.com/TidierOrg/TidierCats.jl/assets/7218387/a10c9ae2-5588-46f5-93c5-8c007f7bb330)

**Comment by drizk1** [comment]
Thank you for catching this, @proudindiv 

Given the error, I think this may be an issue with how `@mutate` is working, so I am going to loop @kdpsingh in to get his take. Depending on his perspective, I can try to find an alternative way for cat_collapse to work. 

As a temporary workaround, the following will still work. 

```
test = cat_collapse(df.CatVar, Dict("Low" => "bad", "Zilch" => "bad"))
df2 = @chain df begin
  @mutate(CatVar = !!test)
end
```

**Comment by kdpsingh** [comment]
Thanks for tagging me. I know exactly why this is happening and will fix it soon. It is an issue in TidierData.jl and not TidierCats.jl

**Comment by kdpsingh** [comment]
This should now be fixed. Feel free to install the latest version of TidierData and confirm.

**Comment by proudindiv** [comment]
Fix works, thank you.
